import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

// add to your project as a module
import { PassportVerifier } from '@gitcoinco/passport-sdk-verifier';
// import {PassportVerifier} from '@gitcoinco/passport-sdk-verifier';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function MyVerifier() {
	const [addressInput, setAddressInput] = useState('');
	const [passport, setPassport] = useState({});

	// create a new instance pointing at Gitcoins mainnet Ceramic node
	const verifier = new PassportVerifier();

	const handleSubmit = (event) => {
		console.log('button clicked');
		event.preventDefault();
		verifier.verifyPassport(addressInput).then((result) => {
			console.log('result is: ', result);
			setPassport(result);
		});
	};

	return (
		<>
			<Head>
				<title>Reader - Gitcoin Passport</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="App">
				<header className="App-header">
					{/* <img src={logo} className="App-logo" alt="logo" /> */}
					<h1>Passport Verifier SDK</h1>
					<p>Enter Wallet Address to verify passport</p>
					<form>
						<input
							type="text"
							name="inputAddress"
							style={{ padding: 12 }}
							// @ts-ignore
							onChange={(e) => setAddressInput(e.target.value)}
							value={addressInput}
						/>
						<button style={{ padding: 12 }} onClick={handleSubmit}>
							Enter
						</button>
					</form>
					{passport && (
						<div
							style={{
								padding: 10,
								marginTop: 10,
								fontSize: 14,
								textAlign: 'left',
							}}
						>
							<h1 style={{ textAlign: 'center' }}>Passport Stamps</h1>
							{
								// @ts-ignore
								passport?.stamps?.length > 0 && (
									<div>
										Stamps:{' '}
										<ul>
											{
												// @ts-ignore
												passport?.stamps?.map((item, index) => {
													return (
														<li key={index}>
															{item.provider}: {item.verified ? '✅' : '❌'}
														</li>
													);
												})
											}
										</ul>
									</div>
								)
							}
						</div>
					)}
				</header>
			</div>
		</>
	);
}
